name: Best_practice_settings
label: Best_practice_settings
description: Example Best_practice_settings
type: panos
extends:

labels:
  service_type: userid

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: FW_NAME
    description: Firewall hostname
    default: panos-01
    type_hint: text
  - name: MGMT_TYPE
    description: firewall management IP type
    default: dhcp-client
    type_hint: dropdown
    help_text: select if the management interface will use DHCP or static configuration
    dd_list:
      - key: dhcp-client
        value: dhcp-client
      - key: static
        value: static
  - name: MGMT_IP
    description: NGFW management IP
    default: 192.0.2.6
    type_hint: ip_address
    toggle_hint:
      source: MGMT_TYPE
      value: static
  - name: MGMT_MASK
    description: NGFW management netmask
    type_hint: ip_address
    default: 255.255.255.0
    toggle_hint:
      source: MGMT_TYPE
      value: static
  - name: MGMT_DG
    description: NGFW management default gateway
    default: 192.0.2.7
    type_hint: ip_address
    toggle_hint:
      source: MGMT_TYPE
      value: static
  - name: NTP_1
    description: primary NTP server
    default: 0.pool.ntp.org
    type_hint: text
  - name: NTP_2
    description: secondary NTP server
    default: 1.pool.ntp.org
    type_hint: text
  - name: ADMINISTRATOR_USERNAME
    description: admin username
    default: adminuser
    type_hint: text
  - name: DNS_1
    description: primary dns server
    default: 8.8.8.8
    type_hint: ip_address
  - name: DNS_2
    description: secondary dns server
    default: 8.8.4.4
    type_hint: ip_address
  - name: SINKHOLE_IPV4
    description: sinkhole FQDN IPv4
    default: sinkhole.paloaltonetworks.com
    type_hint: text
    help_text: FQDN value for the IPV4 sinkhole address used in the anti-spyware security profile
  - name: SINKHOLE_IPV6
    description: sinkhole address IPv6
    default: 2600:5200::1
    type_hint: ip_address
    help_text: IP address for the IPv6 sinkhole used in the anti-spyware security profile
  - name: EMAIL_PROFILE_GATEWAY
    description: email gateway address for critical alerts
    default: 192.0.2.1
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_FROM
    description: from address in email alerts
    default: sentfrom@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: EMAIL_PROFILE_TO
    description: to address in email alerts
    default: sendto@yourdomain.com
    type_hint: text
    help_text: email server profile configuration under Device --> Server Profiles
  - name: SYSLOG_SERVER
    description: syslog server ip address
    default: 192.0.2.2
    type_hint: text
  - name: API_KEY_LIFETIME
    description: lifetime for the api key in minutes
    default: 525600
    type_hint: text
    help_text: sets the expiration period for generated API keys

snippets:
  - name: full.conf
    file: full.conf
