name: Best_practice_settings
label: Best_practice_settings
description: Example Best_practice_settings
type: panos
extends:

labels:
  service_type: userid

variables:
  - name: MGMT_IP
    description: NGFW management IP address
    default: 192.168.0.1
    type_hint: ip_address
  - name: INCLUDE_Security_Profiles
    description: include the predefined OCD Security Profiles
    default: 'no'
    type_hint: dropdown
    help_text: This includeds AV, IPS, VP, URL.
    dd_list:
      - key: 'yes'
        value: 'yes'
      - key: 'no'
        value: 'no'
        
snippets:
 - name: profiles_virus
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/virus
    file: profiles_virus.xml
